/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * ComputerSupportGUI.java
 * 20/4/2013
 * @author Giovanni Antipala x12527037
 */
public class ComputerSupportGUI extends javax.swing.JFrame {

    /**
     * Creates new form ComputerSupportGUI
     */
    public ComputerSupportGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        contact_btn = new javax.swing.JButton();
        msg_btn = new javax.swing.JButton();
        wkshp_btn = new javax.swing.JButton();
        mdl_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        fdb_btn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 3650, 465));
        setMaximumSize(new java.awt.Dimension(365, 465));
        setMinimumSize(new java.awt.Dimension(365, 465));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(355, 440));
        jPanel1.setLayout(null);

        heading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Computing Support");
        jPanel1.add(heading);
        heading.setBounds(100, 30, 154, 22);

        contact_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contact_PNG.png"))); // NOI18N
        contact_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_btnActionPerformed(evt);
            }
        });
        jPanel1.add(contact_btn);
        contact_btn.setBounds(40, 99, 100, 50);

        msg_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Message_PNG.png"))); // NOI18N
        msg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_btnActionPerformed(evt);
            }
        });
        jPanel1.add(msg_btn);
        msg_btn.setBounds(214, 99, 100, 50);

        wkshp_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Workshop_PNG.png"))); // NOI18N
        wkshp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wkshp_btnActionPerformed(evt);
            }
        });
        jPanel1.add(wkshp_btn);
        wkshp_btn.setBounds(40, 204, 100, 50);

        mdl_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Moodle_PNG.png"))); // NOI18N
        mdl_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdl_btnActionPerformed(evt);
            }
        });
        jPanel1.add(mdl_btn);
        mdl_btn.setBounds(214, 204, 100, 50);

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(130, 380, 100, 35);

        fdb_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Feedback_PNG.png"))); // NOI18N
        fdb_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdb_btnActionPerformed(evt);
            }
        });
        jPanel1.add(fdb_btn);
        fdb_btn.setBounds(130, 290, 100, 50);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-290, -310, 670, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contact_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_btnActionPerformed
        // TODO add your handling code here:
        Contact a = new Contact();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_contact_btnActionPerformed

    private void msg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_btnActionPerformed
        // TODO add your handling code here:
        Message b = new Message();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_msg_btnActionPerformed

    private void wkshp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wkshp_btnActionPerformed
        // TODO add your handling code here:
        Workshop c = new Workshop();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_wkshp_btnActionPerformed

    private void mdl_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdl_btnActionPerformed
        // TODO add your handling code here:
        Moodle d = new Moodle();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_mdl_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        MainPageGUI back_A = new MainPageGUI();
        back_A.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void fdb_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdb_btnActionPerformed
        // TODO add your handling code here:
        FeedbackCS fcs = new FeedbackCS();
        fcs.setVisible(true);
        dispose();
    }//GEN-LAST:event_fdb_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerSupportGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel bg;
    private javax.swing.JButton contact_btn;
    private javax.swing.JButton fdb_btn;
    private javax.swing.JLabel heading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mdl_btn;
    private javax.swing.JButton msg_btn;
    private javax.swing.JButton wkshp_btn;
    // End of variables declaration//GEN-END:variables
}
