/*
 * Contact_1.java
 * Rev 1
 * 20/04/2013
 * @author Joanna Bautista, x12374571
 */

/**
 *
 * @author Joanna Bautista, x12374571
 */
public class Contact_1 extends javax.swing.JFrame {

    /**
     * Creates new form Contact
     */
    public Contact_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        learningScontactHeading = new javax.swing.JLabel();
        LearningScontactjBback = new javax.swing.JButton();
        contactSirMikejL = new javax.swing.JLabel();
        learningScontactjL = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 370, 440));
        setMinimumSize(new java.awt.Dimension(370, 440));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        learningScontactHeading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        learningScontactHeading.setForeground(new java.awt.Color(255, 255, 255));
        learningScontactHeading.setText("Contact");
        jPanel1.add(learningScontactHeading);
        learningScontactHeading.setBounds(159, 16, 133, 22);

        LearningScontactjBback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        LearningScontactjBback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LearningScontactjBbackActionPerformed(evt);
            }
        });
        jPanel1.add(LearningScontactjBback);
        LearningScontactjBback.setBounds(159, 404, 100, 35);

        contactSirMikejL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irland1.png"))); // NOI18N
        contactSirMikejL.setText("jLabel1");
        jPanel1.add(contactSirMikejL);
        contactSirMikejL.setBounds(10, 56, 141, 300);

        learningScontactjL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        learningScontactjL.setForeground(new java.awt.Color(255, 255, 255));
        learningScontactjL.setText("<html>\nContact: <br/>\n<br/>\nMichael Goldrick <br/>\nLearning Support Tutor<br/>\n<br/>\n\nPhone: <br/>\n<br/>\n01 6599245  <br/>\n<br/>\n Email: <br/>\n<br/>\n michael.goldrick@ncirl.ie <br/>\n\n</html>");
        jPanel1.add(learningScontactjL);
        learningScontactjL.setBounds(160, 30, 191, 248);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-780, -180, 1170, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LearningScontactjBbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LearningScontactjBbackActionPerformed
        // TODO add your handling code here:
        LearningSupportGUI a = new LearningSupportGUI();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_LearningScontactjBbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LearningScontactjBback;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel contactSirMikejL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel learningScontactHeading;
    private javax.swing.JLabel learningScontactjL;
    // End of variables declaration//GEN-END:variables
}
