/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x11380471
 */
public class DisabilitySupportGUI extends javax.swing.JFrame {

    /**
     * Creates new form DisabilitySupportGUI
     */
    public DisabilitySupportGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        Contact_btn = new javax.swing.JButton();
        Disability_btn = new javax.swing.JButton();
        Needs_btn = new javax.swing.JButton();
        Assisstive_btn = new javax.swing.JButton();
        Library_btn = new javax.swing.JButton();
        Exams_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        Message = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 440, 440));
        setMaximumSize(new java.awt.Dimension(370, 440));
        setMinimumSize(new java.awt.Dimension(370, 440));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        Heading.setBackground(new java.awt.Color(255, 255, 255));
        Heading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Heading.setForeground(new java.awt.Color(255, 255, 255));
        Heading.setText("Disability Support");
        jPanel1.add(Heading);
        Heading.setBounds(110, 20, 138, 22);

        Contact_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contact_PNG.png"))); // NOI18N
        Contact_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contact_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Contact_btn);
        Contact_btn.setBounds(43, 70, 100, 50);

        Disability_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Disability_ACT_PNG.png"))); // NOI18N
        Disability_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Disability_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Disability_btn);
        Disability_btn.setBounds(223, 70, 100, 50);

        Needs_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Needs_Assessment_PNG.png"))); // NOI18N
        Needs_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Needs_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Needs_btn);
        Needs_btn.setBounds(43, 138, 100, 50);

        Assisstive_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assistive_PNG.png"))); // NOI18N
        Assisstive_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assisstive_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Assisstive_btn);
        Assisstive_btn.setBounds(223, 138, 100, 50);

        Library_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_Support_PNG.png"))); // NOI18N
        Library_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Library_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Library_btn);
        Library_btn.setBounds(43, 206, 100, 50);

        Exams_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exams_PNG.png"))); // NOI18N
        Exams_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exams_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Exams_btn);
        Exams_btn.setBounds(223, 206, 100, 50);

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG_3.png"))); // NOI18N
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(132, 375, 100, 35);

        Message.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Message_PNG.png"))); // NOI18N
        Message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageActionPerformed(evt);
            }
        });
        jPanel1.add(Message);
        Message.setBounds(132, 274, 100, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/two.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-80, -220, 470, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Needs_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Needs_btnActionPerformed
        // TODO add your handling code here:
        NeedsAssessment a = new NeedsAssessment();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_Needs_btnActionPerformed

    private void Contact_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contact_btnActionPerformed
        // TODO add your handling code here:
        Contact_2 b = new Contact_2();
        b.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_Contact_btnActionPerformed

    private void Library_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Library_btnActionPerformed
        // TODO add your handling code here:
        LibrarySupport c = new LibrarySupport();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_Library_btnActionPerformed

    private void Disability_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Disability_btnActionPerformed
        // TODO add your handling code here:
        DisabilityAct d = new DisabilityAct();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_Disability_btnActionPerformed

    private void Assisstive_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assisstive_btnActionPerformed
        // TODO add your handling code here:
        AssisstiveTech e = new AssisstiveTech();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Assisstive_btnActionPerformed

    private void Exams_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exams_btnActionPerformed
        // TODO add your handling code here:
        Exams f = new Exams();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_Exams_btnActionPerformed

    private void MessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageActionPerformed
        // TODO add your handling code here:
        Message_1 z = new Message_1();
        z.setVisible(true);
        dispose();
    }//GEN-LAST:event_MessageActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        MainPageGUI back_C = new MainPageGUI();
        back_C.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisabilitySupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisabilitySupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisabilitySupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisabilitySupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisabilitySupportGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Assisstive_btn;
    private javax.swing.JButton Contact_btn;
    private javax.swing.JButton Disability_btn;
    private javax.swing.JButton Exams_btn;
    private javax.swing.JLabel Heading;
    private javax.swing.JButton Library_btn;
    private javax.swing.JButton Message;
    private javax.swing.JButton Needs_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
