/*
 * DyslexiaScreening.java
 * 
 * Rev 1
 * 
 * 20/04/2013
 * 
 * @author Joanna Bautista, x12374571
 */

/**
 *
 * @author Joanna Bautista, x12374571
 */
public class DyslexiaScreening extends javax.swing.JFrame {

    /**
     * Creates new form DyslexiaScreening
     */
    public DyslexiaScreening() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        dysHeadingjL = new javax.swing.JLabel();
        dysbackjbutton = new javax.swing.JButton();
        dysQuestionjB = new javax.swing.JButton();
        dysLinkjL = new javax.swing.JLabel();
        dysDescriptionjL = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 440, 440));
        setMaximumSize(new java.awt.Dimension(370, 440));
        setMinimumSize(new java.awt.Dimension(370, 440));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        dysHeadingjL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dysHeadingjL.setForeground(new java.awt.Color(255, 255, 255));
        dysHeadingjL.setText("Dyslexia Screening");
        jPanel1.add(dysHeadingjL);
        dysHeadingjL.setBounds(117, 28, 146, 22);

        dysbackjbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        dysbackjbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dysbackjbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(dysbackjbutton);
        dysbackjbutton.setBounds(132, 396, 100, 35);

        dysQuestionjB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Questionaires_PNG.png"))); // NOI18N
        dysQuestionjB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dysQuestionjBActionPerformed(evt);
            }
        });
        jPanel1.add(dysQuestionjB);
        dysQuestionjB.setBounds(146, 360, 70, 25);

        dysLinkjL.setForeground(new java.awt.Color(102, 102, 255));
        dysLinkjL.setText("Click the survey button to asnwer the questionnaire.");
        jPanel1.add(dysLinkjL);
        dysLinkjL.setBounds(26, 335, 334, 14);

        dysDescriptionjL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dysDescriptionjL.setForeground(new java.awt.Color(255, 255, 255));
        dysDescriptionjL.setText("<html>\nDyslexia screening is a new service being <br/>\noperated free of charge all students in NCI. <br/>\nThe screening is suggested to students <br/>\nwho feel that they may have difficulty<br/>\nwith reading, writing, spelling or comprehension.<br/>\n<br/>\nTo avail of the service please complete the <br/>\nfollowing survey and bring a printed version to the <br/>\nLearning Support Office <br/>\n(Room 3:11)\n\n</html>");
        jPanel1.add(dysDescriptionjL);
        dysDescriptionjL.setBounds(78, 61, 253, 268);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-820, -50, 1360, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dysbackjbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dysbackjbuttonActionPerformed
        // TODO add your handling code here:
        LearningSupportGUI d = new LearningSupportGUI();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_dysbackjbuttonActionPerformed

    private void dysQuestionjBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dysQuestionjBActionPerformed
        // TODO add your handling code here:
        questionnaire1 k = new questionnaire1();
        k.setVisible(true);
        dispose();
    }//GEN-LAST:event_dysQuestionjBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DyslexiaScreening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DyslexiaScreening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DyslexiaScreening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DyslexiaScreening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DyslexiaScreening().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel dysDescriptionjL;
    private javax.swing.JLabel dysHeadingjL;
    private javax.swing.JLabel dysLinkjL;
    private javax.swing.JButton dysQuestionjB;
    private javax.swing.JButton dysbackjbutton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
