/*
 * LearningSupportGUI.java
 * 
 * Rev 1
 * 
 * 20/04/2013
 * 
 * @author Joanna Bautista, x12374571
 * 
 */

/**
 *
 * @author x12374571
 */
public class LearningSupportGUI extends javax.swing.JFrame {

    /**
     * Creates new form LearningSupportGUI
     */
    public LearningSupportGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LsupportHeading = new javax.swing.JLabel();
        LsupportContactjB = new javax.swing.JButton();
        LsupportManualGjB = new javax.swing.JButton();
        mt_btn = new javax.swing.JButton();
        ds_btn = new javax.swing.JButton();
        hsr_btn = new javax.swing.JButton();
        Lsupportback_btn = new javax.swing.JButton();
        LsupportMessagejB = new javax.swing.JButton();
        jLjL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(370, 440));
        jPanel1.setMinimumSize(new java.awt.Dimension(370, 440));
        jPanel1.setLayout(null);

        LsupportHeading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LsupportHeading.setForeground(new java.awt.Color(255, 255, 255));
        LsupportHeading.setText("Learning Support");
        jPanel1.add(LsupportHeading);
        LsupportHeading.setBounds(114, 28, 135, 22);

        LsupportContactjB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contact_PNG.png"))); // NOI18N
        LsupportContactjB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LsupportContactjBActionPerformed(evt);
            }
        });
        jPanel1.add(LsupportContactjB);
        LsupportContactjB.setBounds(43, 68, 100, 50);

        LsupportManualGjB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManualGuide_PNG.png"))); // NOI18N
        LsupportManualGjB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LsupportManualGjBActionPerformed(evt);
            }
        });
        jPanel1.add(LsupportManualGjB);
        LsupportManualGjB.setBounds(229, 68, 100, 50);

        mt_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MindTraining_PNG.png"))); // NOI18N
        mt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mt_btnActionPerformed(evt);
            }
        });
        jPanel1.add(mt_btn);
        mt_btn.setBounds(43, 145, 100, 50);

        ds_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DyslexiaScreening_PNG.png"))); // NOI18N
        ds_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ds_btnActionPerformed(evt);
            }
        });
        jPanel1.add(ds_btn);
        ds_btn.setBounds(229, 145, 100, 50);

        hsr_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Referencing_PNG.png"))); // NOI18N
        hsr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsr_btnActionPerformed(evt);
            }
        });
        jPanel1.add(hsr_btn);
        hsr_btn.setBounds(43, 223, 100, 50);

        Lsupportback_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        Lsupportback_btn.setPreferredSize(new java.awt.Dimension(100, 35));
        Lsupportback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lsupportback_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Lsupportback_btn);
        Lsupportback_btn.setBounds(140, 370, 100, 35);

        LsupportMessagejB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Message_PNG.png"))); // NOI18N
        LsupportMessagejB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LsupportMessagejBActionPerformed(evt);
            }
        });
        jPanel1.add(LsupportMessagejB);
        LsupportMessagejB.setBounds(229, 223, 100, 50);

        jLjL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(jLjL);
        jLjL.setBounds(-820, -60, 1920, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LsupportContactjBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LsupportContactjBActionPerformed
        // TODO add your handling code here:
        Contact_1 a = new Contact_1();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_LsupportContactjBActionPerformed

    private void hsr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsr_btnActionPerformed
        // TODO add your handling code here:
        HarvardReferencing e = new HarvardReferencing();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_hsr_btnActionPerformed

    private void LsupportManualGjBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LsupportManualGjBActionPerformed
        // TODO add your handling code here:
        ManualGuide b =new ManualGuide();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_LsupportManualGjBActionPerformed

    private void mt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mt_btnActionPerformed
        // TODO add your handling code here:
        MindTraining c = new MindTraining();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_mt_btnActionPerformed

    private void ds_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ds_btnActionPerformed
        // TODO add your handling code here:
        DyslexiaScreening d = new DyslexiaScreening();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_ds_btnActionPerformed

    private void Lsupportback_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lsupportback_btnActionPerformed
        // TODO add your handling code here:
        MainPageGUI back_B = new MainPageGUI();
        back_B.setVisible(true);
        dispose();
    }//GEN-LAST:event_Lsupportback_btnActionPerformed

    private void LsupportMessagejBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LsupportMessagejBActionPerformed
        // TODO add your handling code here:
        LSMessaging j = new LSMessaging();
        j.setVisible(true);
        dispose();
    }//GEN-LAST:event_LsupportMessagejBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearningSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearningSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearningSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearningSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearningSupportGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LsupportContactjB;
    private javax.swing.JLabel LsupportHeading;
    private javax.swing.JButton LsupportManualGjB;
    private javax.swing.JButton LsupportMessagejB;
    private javax.swing.JButton Lsupportback_btn;
    private javax.swing.JButton ds_btn;
    private javax.swing.JButton hsr_btn;
    private javax.swing.JLabel jLjL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mt_btn;
    // End of variables declaration//GEN-END:variables
}
