/* 
 * LSMessaging.java
 * 
 * Rev 1
 * 
 * 20/04/2013
 * 
 * @reference Giovanni Antipala
 * 
 * @author Joanna Bautista, x12374571
 * 
 */

/**
 *
 * @author Joanna Bautista, x12374571
 * 
 */

import java.io.*;
import javax.swing.JOptionPane;

public class LSMessaging extends javax.swing.JFrame {
    private String message;
    private String to;
    private String from;
    
    //declare array
    protected LSMessaging mArray[];
            
    /**
     * Creates new form LSMessaging
     */
    public LSMessaging() {
        initComponents();
        message = new String();
        to = new String();
        from = new String();
        
        //array of messages maximum = 1
        mArray = new LSMessaging[100];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LSMjLabel = new javax.swing.JLabel();
        LSMtojLabel2 = new javax.swing.JLabel();
        LSMfromjLabel3 = new javax.swing.JLabel();
        LSMMessagejLabel4 = new javax.swing.JLabel();
        LSMtotF = new javax.swing.JTextField();
        LSMfromtF = new javax.swing.JTextField();
        LSMmessagetF = new javax.swing.JTextField();
        LSMsendjButton1 = new javax.swing.JButton();
        LSMdisplayjButton = new javax.swing.JButton();
        LSMbackjButton = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        LSMjLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LSMjLabel.setForeground(new java.awt.Color(255, 255, 255));
        LSMjLabel.setText("Message");
        jPanel1.add(LSMjLabel);
        LSMjLabel.setBounds(152, 29, 67, 22);

        LSMtojLabel2.setForeground(new java.awt.Color(255, 255, 255));
        LSMtojLabel2.setText("To:");
        jPanel1.add(LSMtojLabel2);
        LSMtojLabel2.setBounds(18, 72, 30, 14);

        LSMfromjLabel3.setForeground(new java.awt.Color(255, 255, 255));
        LSMfromjLabel3.setText("From:");
        jPanel1.add(LSMfromjLabel3);
        LSMfromjLabel3.setBounds(18, 110, 40, 14);

        LSMMessagejLabel4.setForeground(new java.awt.Color(255, 255, 255));
        LSMMessagejLabel4.setText("Message:");
        jPanel1.add(LSMMessagejLabel4);
        LSMMessagejLabel4.setBounds(18, 163, 60, 14);

        LSMtotF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSMtotFActionPerformed(evt);
            }
        });
        jPanel1.add(LSMtotF);
        LSMtotF.setBounds(134, 69, 197, 20);

        LSMfromtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSMfromtFActionPerformed(evt);
            }
        });
        jPanel1.add(LSMfromtF);
        LSMfromtF.setBounds(134, 107, 197, 20);

        LSMmessagetF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSMmessagetFActionPerformed(evt);
            }
        });
        jPanel1.add(LSMmessagetF);
        LSMmessagetF.setBounds(134, 153, 195, 158);

        LSMsendjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Send_PNG.png"))); // NOI18N
        LSMsendjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSMsendjButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(LSMsendjButton1);
        LSMsendjButton1.setBounds(259, 329, 70, 25);

        LSMdisplayjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Display_PNG.png"))); // NOI18N
        LSMdisplayjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSMdisplayjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LSMdisplayjButton);
        LSMdisplayjButton.setBounds(18, 329, 70, 25);

        LSMbackjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        LSMbackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSMbackjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LSMbackjButton);
        LSMbackjButton.setBounds(134, 389, 100, 35);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-830, -160, 1700, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LSMbackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSMbackjButtonActionPerformed
        // TODO add your handling code here:
        LearningSupportGUI e = new LearningSupportGUI();
        e.setVisible(true);
        dispose();

    }//GEN-LAST:event_LSMbackjButtonActionPerformed

    private void LSMdisplayjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSMdisplayjButtonActionPerformed
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(null, "To: "+ to +"\n From: "+ from +"\n Message: "+ message);
                
                        String name;
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("messages.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            name = br.readLine();
            while (name != null) {
                JOptionPane.showMessageDialog(null, "Name: " + name);
                name = br.readLine();
            }
            br.close();
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_LSMdisplayjButtonActionPerformed

    private void LSMsendjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSMsendjButton1ActionPerformed
        // TODO add your handling code here:
        message = LSMmessagetF.getText();
        to = LSMtotF.getText();
        from = LSMfromtF.getText();
        
        //create  a new object
        LSupport m = new LSupport();
        
        
        //add contents to textfields to m
        m.setTo(to);
        m.setFrom(from);
        m.setMessage(message);
        
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String messages = LSMmessagetF.getText();
        try {
            outFile = new File("message.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(messages);
            bw.newLine();

            bw.close();
            JOptionPane.showMessageDialog(null, "Thank you for sending your message!");
        } catch (IOException e) {
            System.out.println("Error writing to file: " + e);
        }
    }//GEN-LAST:event_LSMsendjButton1ActionPerformed

    private void LSMtotFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSMtotFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LSMtotFActionPerformed

    private void LSMfromtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSMfromtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LSMfromtFActionPerformed

    private void LSMmessagetFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSMmessagetFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LSMmessagetFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LSMessaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LSMessaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LSMessaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LSMessaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new LSMessaging().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LSMMessagejLabel4;
    private javax.swing.JButton LSMbackjButton;
    private javax.swing.JButton LSMdisplayjButton;
    private javax.swing.JLabel LSMfromjLabel3;
    private javax.swing.JTextField LSMfromtF;
    private javax.swing.JLabel LSMjLabel;
    private javax.swing.JTextField LSMmessagetF;
    private javax.swing.JButton LSMsendjButton1;
    private javax.swing.JLabel LSMtojLabel2;
    private javax.swing.JTextField LSMtotF;
    private javax.swing.JLabel bg;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
