/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * MainPageGUI.java
 * 20/4/2013
 * @author Giovanni Antipala x12527037
 */
public class MainPageGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainPageGUI
     */
    public MainPageGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisabilitySupportGUI = new javax.swing.JButton();
        MathsSupportGUI = new javax.swing.JButton();
        ComputerSupportGUI = new javax.swing.JButton();
        LearningSupportGUI = new javax.swing.JButton();
        FeedbackGUI = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 290, 290));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 290, 290));
        setMaximumSize(new java.awt.Dimension(290, 290));
        setMinimumSize(new java.awt.Dimension(290, 290));
        setPreferredSize(new java.awt.Dimension(350, 330));
        setResizable(false);
        getContentPane().setLayout(null);

        DisabilitySupportGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DS_btn.png"))); // NOI18N
        DisabilitySupportGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisabilitySupportGUIActionPerformed(evt);
            }
        });
        getContentPane().add(DisabilitySupportGUI);
        DisabilitySupportGUI.setBounds(30, 200, 75, 25);

        MathsSupportGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MH_btn.png"))); // NOI18N
        MathsSupportGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathsSupportGUIActionPerformed(evt);
            }
        });
        getContentPane().add(MathsSupportGUI);
        MathsSupportGUI.setBounds(30, 240, 75, 25);

        ComputerSupportGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CS_btn.png"))); // NOI18N
        ComputerSupportGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputerSupportGUIActionPerformed(evt);
            }
        });
        getContentPane().add(ComputerSupportGUI);
        ComputerSupportGUI.setBounds(30, 120, 75, 25);

        LearningSupportGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LS_btn.png"))); // NOI18N
        LearningSupportGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LearningSupportGUIActionPerformed(evt);
            }
        });
        getContentPane().add(LearningSupportGUI);
        LearningSupportGUI.setBounds(30, 160, 75, 25);

        FeedbackGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Feedback_Main_PNG.png"))); // NOI18N
        FeedbackGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackGUIActionPerformed(evt);
            }
        });
        getContentPane().add(FeedbackGUI);
        FeedbackGUI.setBounds(200, 20, 70, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NCI_LOGO.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -70, 450, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComputerSupportGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputerSupportGUIActionPerformed
        // TODO add your handling code here:
        ComputerSupportGUI a = new ComputerSupportGUI();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_ComputerSupportGUIActionPerformed

    private void LearningSupportGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LearningSupportGUIActionPerformed
        // TODO add your handling code here:
        LearningSupportGUI b = new LearningSupportGUI();
        b.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_LearningSupportGUIActionPerformed

    private void DisabilitySupportGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisabilitySupportGUIActionPerformed
        // TODO add your handling code here:
        DisabilitySupportGUI c = new DisabilitySupportGUI();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_DisabilitySupportGUIActionPerformed

    private void MathsSupportGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathsSupportGUIActionPerformed
        // TODO add your handling code here:
        MathSupportGUI d = new MathSupportGUI();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_MathsSupportGUIActionPerformed

    private void FeedbackGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackGUIActionPerformed
        // TODO add your handling code here:
        FeedbackGUI z = new FeedbackGUI();
        z.setVisible(true);
        dispose();
    }//GEN-LAST:event_FeedbackGUIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPageGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComputerSupportGUI;
    private javax.swing.JButton DisabilitySupportGUI;
    private javax.swing.JButton FeedbackGUI;
    private javax.swing.JButton LearningSupportGUI;
    private javax.swing.JButton MathsSupportGUI;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
