/*
 * ManualGuideP6.java
 * 
 * Rev 1
 * 
 * 20/04/2013
 * 
 * @author Joanna Bautista, x12374571
 * 
 */

/**
 *
 * @author Joanna Bautista, x12374571
 */
public class ManualGuideP6 extends javax.swing.JFrame {

    /**
     * Creates new form ManualGuideP6
     */
    public ManualGuideP6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manualGheadingLast = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        manualGp6jBback = new javax.swing.JButton();
        manualGp6jBhome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        manualGheadingLast.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manualGheadingLast.setForeground(new java.awt.Color(255, 255, 255));
        manualGheadingLast.setText("Learning Development\n");
        jPanel1.add(manualGheadingLast);
        manualGheadingLast.setBounds(95, 24, 176, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>\nClick the link to continue reading<br/>\n the Learning Development Manual Guide\n</html>");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(65, 113, 246, 34);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("<html>\n<a href=\"https://myncistudent.ncirl.ie/StudentServicesAndSupport/StudentSupport/LearningDevelopment/learning/Learning%20Development%20Manual%2010-11.pdf\"> Learning Development Manual</a>\n</html>");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(65, 208, 238, 22);

        manualGp6jBback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        manualGp6jBback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualGp6jBbackActionPerformed(evt);
            }
        });
        jPanel1.add(manualGp6jBback);
        manualGp6jBback.setBounds(56, 385, 100, 35);

        manualGp6jBhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next_PNG.png"))); // NOI18N
        manualGp6jBhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualGp6jBhomeActionPerformed(evt);
            }
        });
        jPanel1.add(manualGp6jBhome);
        manualGp6jBhome.setBounds(203, 385, 100, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-790, -60, 1370, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
          try{
            String URL ="https://myncistudent.ncirl.ie/StudentServicesAndSupport/StudentSupport/LearningDevelopment/learning/Learning%20Development%20Manual%2010-11.pdf";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch(Exception e){
            System.out.println("error getting url");
        }
    }//GEN-LAST:event_jLabel3MousePressed

    private void manualGp6jBbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualGp6jBbackActionPerformed
        // TODO add your handling code here:
        ManualGuideP5 c = new ManualGuideP5();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_manualGp6jBbackActionPerformed

    private void manualGp6jBhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualGp6jBhomeActionPerformed
        // TODO add your handling code here:
        LearningSupportGUI y = new LearningSupportGUI();
        y.setVisible(true);
        dispose();
    }//GEN-LAST:event_manualGp6jBhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManualGuideP6().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manualGheadingLast;
    private javax.swing.JButton manualGp6jBback;
    private javax.swing.JButton manualGp6jBhome;
    // End of variables declaration//GEN-END:variables
}
