/*
 * ManualGuideP2.java
 * 
 * Rev 1
 * 
 * 20/04/2013
 * 
 * @author Joanna Bautista, x12374571
 */

public class ManualGuideP2 extends javax.swing.JFrame {

    /**
     * Creates new form ManualGuideP2
     */
    public ManualGuideP2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manualGP2jBback = new javax.swing.JButton();
        manualGP2jBnext = new javax.swing.JButton();
        manualGjL2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(370, 440));
        jPanel1.setLayout(null);

        manualGP2jBback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        manualGP2jBback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualGP2jBbackActionPerformed(evt);
            }
        });
        jPanel1.add(manualGP2jBback);
        manualGP2jBback.setBounds(42, 387, 100, 35);

        manualGP2jBnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next_PNG.png"))); // NOI18N
        manualGP2jBnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualGP2jBnextActionPerformed(evt);
            }
        });
        jPanel1.add(manualGP2jBnext);
        manualGP2jBnext.setBounds(232, 387, 100, 35);

        manualGjL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.jpg"))); // NOI18N
        manualGjL2.setText("jLabel2");
        jPanel1.add(manualGjL2);
        manualGjL2.setBounds(42, 46, 290, 330);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-810, -140, 1200, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manualGP2jBbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualGP2jBbackActionPerformed
        // TODO add your handling code here:
        ManualGuide c = new ManualGuide();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_manualGP2jBbackActionPerformed

    private void manualGP2jBnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualGP2jBnextActionPerformed
        // TODO add your handling code here:
        ManualGuideP3 e = new ManualGuideP3();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_manualGP2jBnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManualGuideP2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manualGP2jBback;
    private javax.swing.JButton manualGP2jBnext;
    private javax.swing.JLabel manualGjL2;
    // End of variables declaration//GEN-END:variables
}
