/*
 * ManualGuideP3.java
 * 
 * Rev 1
 * 
 * 20/04/2013
 * 
 * @author Joanna Bautista, x12374571
 */

/**
 *
 * @author Joanna Bautista x12374571
 */
public class ManualGuideP3 extends javax.swing.JFrame {

    /**
     * Creates new form ManualGuideP3
     */
    public ManualGuideP3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MgjPanel1 = new javax.swing.JPanel();
        manualGjL3 = new javax.swing.JLabel();
        manualGP3jBback = new javax.swing.JButton();
        manualGP3jBnext = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        MgjPanel1.setBackground(new java.awt.Color(0, 0, 0));
        MgjPanel1.setLayout(null);

        manualGjL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.jpg"))); // NOI18N
        manualGjL3.setText("jLabel1");
        MgjPanel1.add(manualGjL3);
        manualGjL3.setBounds(36, 43, 290, 330);

        manualGP3jBback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        manualGP3jBback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualGP3jBbackActionPerformed(evt);
            }
        });
        MgjPanel1.add(manualGP3jBback);
        manualGP3jBback.setBounds(36, 384, 100, 35);

        manualGP3jBnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next_PNG.png"))); // NOI18N
        manualGP3jBnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualGP3jBnextActionPerformed(evt);
            }
        });
        MgjPanel1.add(manualGP3jBnext);
        manualGP3jBnext.setBounds(226, 384, 100, 35);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        MgjPanel1.add(bg);
        bg.setBounds(-810, -100, 1210, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MgjPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MgjPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manualGP3jBbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualGP3jBbackActionPerformed
        // TODO add your handling code here:
        ManualGuideP2 b = new ManualGuideP2();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_manualGP3jBbackActionPerformed

    private void manualGP3jBnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualGP3jBnextActionPerformed
        // TODO add your handling code here:
        ManualGuideP4 b = new ManualGuideP4();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_manualGP3jBnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManualGuideP3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MgjPanel1;
    private javax.swing.JLabel bg;
    private javax.swing.JButton manualGP3jBback;
    private javax.swing.JButton manualGP3jBnext;
    private javax.swing.JLabel manualGjL3;
    // End of variables declaration//GEN-END:variables
}
