/*
 *ManualGuideP5.java
 * 
 * Rev 1
 * 
 * 20/04/2013
 * 
 * @author Joanna Bautista, x12374571
 */

/**
 *
 * @author Joanna Bautista, x12374571
 */
public class ManualGuideP5 extends javax.swing.JFrame {

    /**
     * Creates new form ManualGuideP5
     */
    public ManualGuideP5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manualGjL5 = new javax.swing.JLabel();
        manualGP5jBback = new javax.swing.JButton();
        manualGP5jBnext = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        manualGjL5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/6.jpg"))); // NOI18N
        manualGjL5.setText("jLabel1");
        jPanel1.add(manualGjL5);
        manualGjL5.setBounds(43, 45, 290, 330);

        manualGP5jBback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        manualGP5jBback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualGP5jBbackActionPerformed(evt);
            }
        });
        jPanel1.add(manualGP5jBback);
        manualGP5jBback.setBounds(43, 386, 100, 35);

        manualGP5jBnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next_PNG.png"))); // NOI18N
        manualGP5jBnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualGP5jBnextActionPerformed(evt);
            }
        });
        jPanel1.add(manualGP5jBnext);
        manualGP5jBnext.setBounds(233, 386, 100, 35);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-800, -140, 1230, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manualGP5jBbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualGP5jBbackActionPerformed
        // TODO add your handling code here:
        ManualGuideP4 b = new ManualGuideP4();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_manualGP5jBbackActionPerformed

    private void manualGP5jBnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualGP5jBnextActionPerformed
        // TODO add your handling code here:
        ManualGuideP6 h = new ManualGuideP6();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_manualGP5jBnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManualGuideP5().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manualGP5jBback;
    private javax.swing.JButton manualGP5jBnext;
    private javax.swing.JLabel manualGjL5;
    // End of variables declaration//GEN-END:variables
}
