/*
 * ManualGuideP1.java
 * 
 * Rev 1
 * 
 * 20/04/2013
 * 
 * @author Joanna Bautista, x12374571
 */

/**
 *
 * @author Joanna Bautista, x12374571
 */
public class ManualGuideP1 extends javax.swing.JFrame {

    /**
     * Creates new form ManualGuideP1
     */
    public ManualGuideP1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manualGjL1 = new javax.swing.JLabel();
        manualGP1jBback = new javax.swing.JButton();
        manualGP1jBnext = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        manualGjL1.setForeground(new java.awt.Color(255, 255, 255));
        manualGjL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.jpg"))); // NOI18N
        jPanel1.add(manualGjL1);
        manualGjL1.setBounds(40, 40, 290, 330);

        manualGP1jBback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        manualGP1jBback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualGP1jBbackActionPerformed(evt);
            }
        });
        jPanel1.add(manualGP1jBback);
        manualGP1jBback.setBounds(27, 388, 100, 35);

        manualGP1jBnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next_PNG.png"))); // NOI18N
        manualGP1jBnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualGP1jBnextActionPerformed(evt);
            }
        });
        jPanel1.add(manualGP1jBnext);
        manualGP1jBnext.setBounds(234, 388, 100, 35);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-850, -30, 1400, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manualGP1jBnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualGP1jBnextActionPerformed
        // TODO add your handling code here:
        ManualGuideP2 b = new ManualGuideP2();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_manualGP1jBnextActionPerformed

    private void manualGP1jBbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualGP1jBbackActionPerformed
        // TODO add your handling code here:
        ManualGuide b = new ManualGuide();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_manualGP1jBbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManualGuideP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ManualGuideP1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manualGP1jBback;
    private javax.swing.JButton manualGP1jBnext;
    private javax.swing.JLabel manualGjL1;
    // End of variables declaration//GEN-END:variables
}
