/*
 * ManualGuide.java
 * 
 * Rev 1
 * 
 * 20/04/2013
 * 
 * @author Joanna Bautista, x12374571
 * 
 */

/**
 *
 * @author Joanna Bautista, x12374571
 */
public class ManualGuide extends javax.swing.JFrame {

    /**
     * Creates new form ManualGuide
     */
    public ManualGuide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JPanel();
        manualGheading = new javax.swing.JLabel();
        manualGjBback = new javax.swing.JButton();
        ManualGjL = new javax.swing.JLabel();
        manualGjBnext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 370, 440));
        setMinimumSize(new java.awt.Dimension(370, 440));
        setResizable(false);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.setPreferredSize(new java.awt.Dimension(370, 440));
        back.setLayout(null);

        manualGheading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manualGheading.setForeground(new java.awt.Color(255, 255, 255));
        manualGheading.setText("Manual Guide");
        back.add(manualGheading);
        manualGheading.setBounds(130, 20, 107, 22);

        manualGjBback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        manualGjBback.setPreferredSize(new java.awt.Dimension(100, 35));
        manualGjBback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualGjBbackActionPerformed(evt);
            }
        });
        back.add(manualGjBback);
        manualGjBback.setBounds(40, 390, 100, 35);

        ManualGjL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        back.add(ManualGjL);
        ManualGjL.setBounds(40, 50, 290, 330);

        manualGjBnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next_PNG.png"))); // NOI18N
        manualGjBnext.setMaximumSize(new java.awt.Dimension(100, 35));
        manualGjBnext.setMinimumSize(new java.awt.Dimension(100, 35));
        manualGjBnext.setPreferredSize(new java.awt.Dimension(100, 35));
        manualGjBnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualGjBnextActionPerformed(evt);
            }
        });
        back.add(manualGjBnext);
        manualGjBnext.setBounds(230, 390, 100, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        back.add(jLabel1);
        jLabel1.setBounds(-810, -110, 1370, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manualGjBnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualGjBnextActionPerformed
        ManualGuideP1 b = new ManualGuideP1();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_manualGjBnextActionPerformed

    private void manualGjBbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualGjBbackActionPerformed
        // TODO add your handling code here:
        LearningSupportGUI b = new LearningSupportGUI();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_manualGjBbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManualGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManualGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManualGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManualGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManualGuide().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ManualGjL;
    private javax.swing.JPanel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel manualGheading;
    private javax.swing.JButton manualGjBback;
    private javax.swing.JButton manualGjBnext;
    // End of variables declaration//GEN-END:variables
}
