/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x12331271
 */
public class MathSupportGUI extends javax.swing.JFrame {

    /**
     * Creates new form MathSupportGUI
     */
    public MathSupportGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        contact_btn = new javax.swing.JButton();
        MessagingButton = new javax.swing.JButton();
        Workshops = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 370, 470));
        setMaximumSize(new java.awt.Dimension(370, 470));
        setMinimumSize(new java.awt.Dimension(370, 470));
        setPreferredSize(new java.awt.Dimension(370, 470));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        Heading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Heading.setText("Maths Support");
        jPanel1.add(Heading);
        Heading.setBounds(123, 30, 115, 22);

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(128, 394, 100, 35);

        contact_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contact_PNG.png"))); // NOI18N
        contact_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_btnActionPerformed(evt);
            }
        });
        jPanel1.add(contact_btn);
        contact_btn.setBounds(51, 104, 100, 50);

        MessagingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Message_PNG.png"))); // NOI18N
        MessagingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessagingButtonActionPerformed(evt);
            }
        });
        jPanel1.add(MessagingButton);
        MessagingButton.setBounds(206, 104, 100, 50);

        Workshops.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Workshop_PNG.png"))); // NOI18N
        Workshops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkshopsActionPerformed(evt);
            }
        });
        jPanel1.add(Workshops);
        Workshops.setBounds(51, 212, 100, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recommended_PNG.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(206, 212, 100, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dots.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-650, -160, 1340, 910);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contact_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_btnActionPerformed
        // TODO add your handling code here:
        Contact_3 a = new Contact_3();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_contact_btnActionPerformed

    private void MessagingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessagingButtonActionPerformed
        // TODO add your handling code here:
        Messaging a = new Messaging();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_MessagingButtonActionPerformed

    private void WorkshopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkshopsActionPerformed
        // TODO add your handling code here:
        Workshops c = new Workshops();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_WorkshopsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Reading d = new Reading();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        MainPageGUI back_D = new MainPageGUI();
        back_D.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathSupportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathSupportGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JButton MessagingButton;
    private javax.swing.JButton Workshops;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton contact_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
