
import java.io.*;
import javax.swing.JOptionPane;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x12331271
 */


public class Messaging extends javax.swing.JFrame {
        private String nLbl;
        private String SLbl;
        private String Mlbl;
        
    protected Messaging mArray[];
    
    
    public Messaging() {
        initComponents();
        nLbl = new String();
        SLbl = new String();
        Mlbl = new String();
        
        mArray = new Messaging[100];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameTF = new javax.swing.JTextField();
        StudentTF = new javax.swing.JTextField();
        MessageTF = new javax.swing.JTextField();
        Send = new javax.swing.JButton();
        Show = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        FileBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 400, 510));
        setMaximumSize(new java.awt.Dimension(400, 510));
        setMinimumSize(new java.awt.Dimension(400, 510));
        setPreferredSize(new java.awt.Dimension(400, 510));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });
        jPanel1.add(NameTF);
        NameTF.setBounds(102, 73, 240, 20);
        jPanel1.add(StudentTF);
        StudentTF.setBounds(102, 115, 242, 20);
        jPanel1.add(MessageTF);
        MessageTF.setBounds(102, 153, 242, 189);

        Send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Send_PNG.png"))); // NOI18N
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });
        jPanel1.add(Send);
        Send.setBounds(102, 353, 70, 25);

        Show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Display_PNG.png"))); // NOI18N
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });
        jPanel1.add(Show);
        Show.setBounds(190, 353, 70, 25);

        jLabel1.setText("Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 70, 82, 27);

        jLabel2.setText("Student Number:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 118, 82, 14);

        jLabel3.setText("Message:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 153, 82, 24);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Message");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 10, 189, 24);

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(160, 406, 100, 35);

        FileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Load_TXT_PNG.png"))); // NOI18N
        FileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileBtnActionPerformed(evt);
            }
        });
        jPanel1.add(FileBtn);
        FileBtn.setBounds(278, 353, 70, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dots.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-420, -50, 1010, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        // TODO add your handling code here:
         nLbl = NameTF.getText();
         SLbl = StudentTF.getText();
         Mlbl = MessageTF.getText();
         
         IntClass m = new IntClass();
         
         m.setName(nLbl);
         m.setStudentNumber(SLbl);
         m.setMessage(Mlbl);
         
           File outFile;
        FileWriter fw;
        BufferedWriter bw;
        
        String to = NameTF.getText();
        String from = StudentTF.getText();
        String msg = MessageTF.getText();
                
        try{
            outFile = new File("Message.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);
            
            bw.write(to);
            bw.newLine();
            
            bw.write(from);
            bw.newLine();
              
            bw.write(msg);
            bw.newLine();
            bw.close();
        
        } catch(IOException e){
            System.out.println("Error writing to file: " + e);
        }
         
         
         
    }//GEN-LAST:event_SendActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        MathSupportGUI a = new MathSupportGUI();
        a.setVisible(true);
        dispose();
                
    }//GEN-LAST:event_back_btnActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "To: "+ nLbl +"\n From: "+ SLbl +"\n Message: "+ Mlbl);
    }//GEN-LAST:event_ShowActionPerformed

    private void FileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileBtnActionPerformed
        // TODO add your handling code here:  String to;
        String nLbl;
        String SLbl;
        String Mlbl;
        File inFile;
        FileReader fr;
        BufferedReader br;
        
        try{ 
            inFile = new File("Message.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);
            
            nLbl = br.readLine();
            SLbl = br.readLine();
            Mlbl = br.readLine();
            
            while((nLbl != null) || (SLbl != null) || (Mlbl != null)){
                JOptionPane.showMessageDialog(null, "To: "+ nLbl +"\n From: "+ SLbl +"\n Message: "+ Mlbl);
                nLbl = br.readLine();               
                SLbl = br.readLine();
                Mlbl = br.readLine();
            }
            br.close();
            
        }catch (IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_FileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Messaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Messaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Messaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Messaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Messaging().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FileBtn;
    private javax.swing.JTextField MessageTF;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton Send;
    private javax.swing.JButton Show;
    private javax.swing.JTextField StudentTF;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
