
import java.io.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Message.java
 * 20/4/2013
 * @author Giovanni Antipala x12527037
 */
public class Message extends javax.swing.JFrame {
    private String to;
    private String from;
    private String msg;
    
    //declare array
    protected Message mArray[];

    /**
     * Creates new form Message
     */
    public Message() {
        initComponents();
        to = new String();
        from = new String();
        msg = new String();
        
      //array of messages maxmimum: 1!
        mArray = new Message[100];
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        to_lbl = new javax.swing.JLabel();
        From = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        to_tf = new javax.swing.JTextField();
        from_tf = new javax.swing.JTextField();
        msg_tf = new javax.swing.JTextField();
        send_btn = new javax.swing.JButton();
        display_btn = new javax.swing.JButton();
        load_btn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 370, 440));
        setMaximumSize(new java.awt.Dimension(370, 440));
        setMinimumSize(new java.awt.Dimension(370, 440));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        heading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Message");
        jPanel1.add(heading);
        heading.setBounds(156, 25, 67, 22);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(162, 534, 100, 35);

        to_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        to_lbl.setForeground(new java.awt.Color(255, 255, 255));
        to_lbl.setText("To:");
        jPanel1.add(to_lbl);
        to_lbl.setBounds(85, 84, 21, 17);

        From.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        From.setForeground(new java.awt.Color(255, 255, 255));
        From.setText("From:");
        jPanel1.add(From);
        From.setBounds(69, 122, 37, 17);

        Message.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Message.setForeground(new java.awt.Color(255, 255, 255));
        Message.setText("Message:");
        jPanel1.add(Message);
        Message.setBounds(50, 160, 56, 17);

        to_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_tfActionPerformed(evt);
            }
        });
        jPanel1.add(to_tf);
        to_tf.setBounds(124, 84, 200, 20);
        jPanel1.add(from_tf);
        from_tf.setBounds(124, 122, 200, 20);

        msg_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_tfActionPerformed(evt);
            }
        });
        jPanel1.add(msg_tf);
        msg_tf.setBounds(124, 160, 198, 213);

        send_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Send_PNG.png"))); // NOI18N
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });
        jPanel1.add(send_btn);
        send_btn.setBounds(80, 390, 70, 25);

        display_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Display_PNG.png"))); // NOI18N
        display_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_btnActionPerformed(evt);
            }
        });
        jPanel1.add(display_btn);
        display_btn.setBounds(260, 390, 70, 25);

        load_btn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        load_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Load_TXT_PNG.png"))); // NOI18N
        load_btn.setPreferredSize(new java.awt.Dimension(70, 25));
        load_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_btnActionPerformed(evt);
            }
        });
        jPanel1.add(load_btn);
        load_btn.setBounds(170, 390, 70, 25);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-290, -220, 660, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        ComputerSupportGUI d = new ComputerSupportGUI();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        // TODO add your handling code here:
        //Get text from TextFields
        to = to_tf.getText();
        from = from_tf.getText();
        msg = msg_tf.getText();
        
        //create a new object
        ComputerSupport m = new ComputerSupport();
        
        //add contents to textfields to m
        m.setTo(to);
        m.setFrom(from);
        m.setMsg(msg);
        
        File outFile;
        FileWriter fw;
        BufferedWriter bw;
        
        String to = to_tf.getText();
        String from = from_tf.getText();
        String msg = msg_tf.getText();
                
        try{
            outFile = new File("Message.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);
            
            bw.write(to);
            bw.newLine();
            
            bw.write(from);
            bw.newLine();
              
            bw.write(msg);
            bw.newLine();
            bw.close();
            
            JOptionPane.showMessageDialog(null, "Message sent!");
        
        } catch(IOException e){
            System.out.println("Error writing to file: " + e);
        }
        
        
        
    }//GEN-LAST:event_send_btnActionPerformed

    private void msg_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msg_tfActionPerformed

    private void display_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_btnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "To: "+ to +"\n From: "+ from +"\n Message: "+ msg);       
    }//GEN-LAST:event_display_btnActionPerformed

    private void load_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_btnActionPerformed
        // TODO add your handling code here:String to;
        String to;
        String from;
        String msg;
        File inFile;
        FileReader fr;
        BufferedReader br;
        
        try{ 
            inFile = new File("Message.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);
            
            to = br.readLine();
            from = br.readLine();
            msg = br.readLine();
            
            while((to != null) || (from != null) || (msg != null)){
                JOptionPane.showMessageDialog(null, "To: "+ to +"\n From: "+ from +"\n Message: "+ msg);
                to = br.readLine();               
                from = br.readLine();
                msg = br.readLine();
            }
            br.close();
            
        }catch (IOException e){
            System.out.println(e);
        }
        
        
                                   
    }//GEN-LAST:event_load_btnActionPerformed

    private void to_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to_tfActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Message().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel From;
    private javax.swing.JLabel Message;
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JButton display_btn;
    private javax.swing.JTextField from_tf;
    private javax.swing.JLabel heading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton load_btn;
    private javax.swing.JTextField msg_tf;
    private javax.swing.JButton send_btn;
    private javax.swing.JLabel to_lbl;
    private javax.swing.JTextField to_tf;
    // End of variables declaration//GEN-END:variables
}
