/*
 * MindTraining.java
 * 
 * Rev 1
 * 
 * 20/04/2013
 * 
 * @author Joanna Bautista, x12374571
 */

/**
 *
 * @author Joanna Bautista, x12374571
 */
public class MindTraining extends javax.swing.JFrame {

    /**
     * Creates new form MindTraining
     */
    public MindTraining() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mindTrainingHeadingjL = new javax.swing.JLabel();
        mindTrainingjBback = new javax.swing.JButton();
        edysjB = new javax.swing.JButton();
        alertsjB = new javax.swing.JButton();
        mindTrainingDescjL = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 370, 440));
        setMaximumSize(new java.awt.Dimension(370, 440));
        setMinimumSize(new java.awt.Dimension(370, 440));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        mindTrainingHeadingjL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mindTrainingHeadingjL.setForeground(new java.awt.Color(255, 255, 255));
        mindTrainingHeadingjL.setText("Mind Training");
        jPanel1.add(mindTrainingHeadingjL);
        mindTrainingHeadingjL.setBounds(119, 29, 124, 22);

        mindTrainingjBback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        mindTrainingjBback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mindTrainingjBbackActionPerformed(evt);
            }
        });
        jPanel1.add(mindTrainingjBback);
        mindTrainingjBback.setBounds(147, 393, 100, 35);

        edysjB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EDYSGATE_PNG.png"))); // NOI18N
        edysjB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edysjBActionPerformed(evt);
            }
        });
        jPanel1.add(edysjB);
        edysjB.setBounds(37, 302, 70, 25);

        alertsjB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alert_PNG.png"))); // NOI18N
        alertsjB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertsjBActionPerformed(evt);
            }
        });
        jPanel1.add(alertsjB);
        alertsjB.setBounds(255, 302, 70, 25);

        mindTrainingDescjL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mindTrainingDescjL.setForeground(new java.awt.Color(255, 255, 255));
        mindTrainingDescjL.setText("<html>\n\nWhilst the practice of mind training has been made </br>\npopular in recent times through the usage of gaming </br>\n culture, the principles behind such daily mental </br>\nworkouts has a long history, dating back to ancient </br>\nGreece and China. This lineage of puzzling, </br>\n logic and numeracy can help every learner improve </br>\n their working memory and processing speed, which </br>\n is a crucial element during not only exam revision, </br>\n but exam performance. To begin your own mental </br>\nworkout, try the below links from home. </br>\n \n©NCI Student Support</br>\n\n</html>");
        jPanel1.add(mindTrainingDescjL);
        mindTrainingDescjL.setBounds(37, 69, 304, 222);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-820, -70, 1390, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mindTrainingjBbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mindTrainingjBbackActionPerformed
        // TODO add your handling code here:
        LearningSupportGUI c = new LearningSupportGUI();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_mindTrainingjBbackActionPerformed

    private void edysjBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edysjBActionPerformed
        // TODO add your handling code here:
        EdysgateMindTraining f = new EdysgateMindTraining();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_edysjBActionPerformed

    private void alertsjBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertsjBActionPerformed
        AlertMindTraining j = new AlertMindTraining();
        j.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_alertsjBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MindTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MindTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MindTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MindTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MindTraining().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alertsjB;
    private javax.swing.JLabel bg;
    private javax.swing.JButton edysjB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mindTrainingDescjL;
    private javax.swing.JLabel mindTrainingHeadingjL;
    private javax.swing.JButton mindTrainingjBback;
    // End of variables declaration//GEN-END:variables
}
