/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Moodle.java
 * 20/4/2013
 * @author Giovanni Antipala x12527037
 */
public class Moodle extends javax.swing.JFrame {
    private String URL;

    /**
     * Creates new form Moodle
     */
    public Moodle() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 370, 440));
        setMaximumSize(new java.awt.Dimension(370, 440));
        setMinimumSize(new java.awt.Dimension(370, 440));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(370, 440));
        jPanel1.setMinimumSize(new java.awt.Dimension(370, 440));
        jPanel1.setLayout(null);

        heading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Moodle");
        jPanel1.add(heading);
        heading.setBounds(150, 30, 57, 22);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(150, 370, 100, 35);

        p1.setBackground(new java.awt.Color(0, 0, 0));
        p1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 255, 255));
        p1.setText("<html>  The Computing Support Service also has a Moodle page where you can find a schedule of  extra classes and Drop in Workshop hours as well as past exam papers and revision  material for some modules.  </html>");
        jPanel1.add(p1);
        p1.setBounds(10, 55, 349, 79);

        p2.setBackground(new java.awt.Color(0, 0, 0));
        p2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 255, 255));
        p2.setText("<html> Enroll yourself on the Computing Support Moodle page by following this link:<br><br>");
        jPanel1.add(p2);
        p2.setBounds(10, 120, 330, 78);

        p3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        p3.setForeground(new java.awt.Color(255, 255, 255));
        p3.setText("<html>\n<br>\n<b><a href=\"https://moodle.ncirl.ie/course/view.php?id=1199\">Moodle - Computing Support page</a></b>\n</html>\n");
        p3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p3MousePressed(evt);
            }
        });
        jPanel1.add(p3);
        p3.setBounds(10, 160, 350, 30);

        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        bg.setText("<html>\nhttps://moodle.ncirl.ie/course/view.php?id=1199\n</html>\n");
        jPanel1.add(bg);
        bg.setBounds(-280, -300, 720, 820);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 370, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        ComputerSupportGUI e = new ComputerSupportGUI();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void p3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p3MousePressed
        // TODO add your handling code here:
        try{
            String URL ="https://moodle.ncirl.ie/course/view.php?id=1199";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch(Exception e){
            System.out.println("error getting url");
        }                             
    }//GEN-LAST:event_p3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moodle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moodle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moodle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moodle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Moodle().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel heading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    // End of variables declaration//GEN-END:variables
}
