/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gio
 */
public class WorkshopP2 extends javax.swing.JFrame {

    /**
     * Creates new form WorkshopP2
     */
    public WorkshopP2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        wct = new javax.swing.JLabel();
        diw = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bck_btn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(350, 550));
        setMinimumSize(new java.awt.Dimension(350, 550));
        setPreferredSize(new java.awt.Dimension(350, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(350, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(350, 550));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 550));
        jPanel1.setLayout(null);

        wct.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        wct.setForeground(new java.awt.Color(255, 255, 255));
        wct.setText("<html> <b>Whole Class Tutorials</b><br><br> If a class are finding a particular module or topic difficult and need an additional tutorial,  the lecturer or class rep may contact the Support Tutor who will then schedule an extra  tutorial for the whole class. </html>");
        jPanel1.add(wct);
        wct.setBounds(30, 20, 290, 90);

        diw.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        diw.setForeground(new java.awt.Color(255, 255, 255));
        diw.setText("<html>\n<b>Drop In Workshops</b><br><br>\nThe Computing Support Service runs weekly support workshops for first year students in \nComputer Programming. These sessions are scheduled in your timetable from week 3 or \n4 onwards. If you have a small question or query you can always just pop into the \nsession and ask or you might simply come along and use the time to work on additional \nprogrammes or project work with the support of the tutor. No appointment needed! \nWhere additional tutorials on particular topics are requested, the workshops can also be \nused as an additional tutorial session instead. \n</html>");
        jPanel1.add(diw);
        diw.setBounds(30, 110, 310, 180);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>\n<b>Drop In Workshops</b><br><br>\nThe Computing Support Service runs weekly support workshops for first year students in \nComputer Programming. These sessions are scheduled in your timetable from week 3 or \n4 onwards. If you have a small question or query you can always just pop into the \nsession and ask or you might simply come along and use the time to work on additional \nprogrammes or project work with the support of the tutor. No appointment needed! \nWhere additional tutorials on particular topics are requested, the workshops can also be \nused as an additional tutorial session instead.\n</html>");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 280, 310, 170);

        bck_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        bck_btn.setMaximumSize(new java.awt.Dimension(100, 35));
        bck_btn.setMinimumSize(new java.awt.Dimension(100, 35));
        bck_btn.setPreferredSize(new java.awt.Dimension(100, 35));
        bck_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck_btnActionPerformed(evt);
            }
        });
        jPanel1.add(bck_btn);
        bck_btn.setBounds(130, 470, 100, 35);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-310, -250, 660, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bck_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck_btnActionPerformed
        // TODO add your handling code here:
        Workshop w = new Workshop();
        w.setVisible(true);
        dispose();
    }//GEN-LAST:event_bck_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkshopP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkshopP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkshopP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkshopP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkshopP2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bck_btn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel diw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel wct;
    // End of variables declaration//GEN-END:variables
}
