/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Workshop.java
 * 20/4/2013
 * @author Giovanni Antipala x12527037
 */
public class Workshop extends javax.swing.JFrame {

    /**
     * Creates new form Workshop
     */
    public Workshop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        swat = new javax.swing.JLabel();
        o_t_o = new javax.swing.JLabel();
        sgt = new javax.swing.JLabel();
        nxt_btn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFocusTraversalPolicyProvider(true);
        setMaximumSize(new java.awt.Dimension(350, 520));
        setMinimumSize(new java.awt.Dimension(350, 520));
        setPreferredSize(new java.awt.Dimension(350, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(350, 520));
        jPanel1.setMinimumSize(new java.awt.Dimension(350, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 520));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(null);

        heading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Workshop");
        heading.setMaximumSize(new java.awt.Dimension(350, 520));
        heading.setMinimumSize(new java.awt.Dimension(350, 520));
        jPanel1.add(heading);
        heading.setBounds(121, 20, 79, 22);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_PNG.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(64, 436, 100, 35);

        swat.setBackground(new java.awt.Color(0, 0, 0));
        swat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        swat.setForeground(new java.awt.Color(255, 255, 255));
        swat.setText("<html> <b>SWAT Workshops</b><br><br>  In semester one the Computing Support Service runs a series of workshops for first year students focussing on the skills needed when settling into a new college course. These include topics such as, touch typing, referencing, research etc. These sessions are not mandatory but attendance is strongly recommended. <br>  </html>");
        jPanel1.add(swat);
        swat.setBounds(10, 48, 330, 111);

        o_t_o.setBackground(new java.awt.Color(0, 0, 0));
        o_t_o.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        o_t_o.setForeground(new java.awt.Color(255, 255, 255));
        o_t_o.setText("<html>  <b>One to One & Small Group Tutorials</b><br><br>  The Computing Support Tutor is available to work with students on a one to one or small group basis. Students that find that they are falling behind in a module or that are finding a particular topic difficult to understand should contact the Support Tutor for an appointment and get caught up before it becomes a problem.  </html>");
        jPanel1.add(o_t_o);
        o_t_o.setBounds(10, 165, 340, 39);

        sgt.setBackground(new java.awt.Color(0, 0, 0));
        sgt.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        sgt.setForeground(new java.awt.Color(255, 255, 255));
        sgt.setText("<html>\n\n<b>One to One & Small Group Tutorials</b><br><br>\nThe Computing Support Tutor is available to work with students on a one to one or small group basis. Students that find that they are falling behind in a module or that are finding a particular topic difficult to understand should contact the Support Tutor for an appointment and get caught up before it becomes a problem.\n\n</html>");
        jPanel1.add(sgt);
        sgt.setBounds(10, 262, 330, 111);

        nxt_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next_PNG.png"))); // NOI18N
        nxt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt_btnActionPerformed(evt);
            }
        });
        jPanel1.add(nxt_btn);
        nxt_btn.setBounds(182, 436, 100, 35);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/One.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-290, -220, 660, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        ComputerSupportGUI b = new ComputerSupportGUI();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void nxt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt_btnActionPerformed
        // TODO add your handling code here:
        WorkshopP2 p2 = new WorkshopP2();
        p2.setVisible(true);
        dispose();
    }//GEN-LAST:event_nxt_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Workshop().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel heading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nxt_btn;
    private javax.swing.JLabel o_t_o;
    private javax.swing.JLabel sgt;
    private javax.swing.JLabel swat;
    // End of variables declaration//GEN-END:variables
}
